Presign options
adobe/aio-lib-files pull request #56
Opened 2020-08-19 09:24 UTC by sandeep-paliwal

Support passing permissions to generate presign URL
supported permissions
READ, WRITE, DELETE  (Default READ)

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

unit tests and manual tests

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ x] My code follows the code style of this project.
- [ x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x ] I have read the **CONTRIBUTING** document.
- [ x] I have added tests to cover my changes.
- [ x] All new and existing tests passed.

2020-08-19 09:32 UTC, moritzraho requested changes
2 minor comments in code.

Also could you regenerate the api doc + add the permission usage in the README ?

2020-08-19 09:32 UTC, moritzraho commented on lib/Files.js
> +const _permissions = {
Here you can define a static constant instead: `Files.Permissions = {}` that way it is exposed to the user too

2020-08-19 09:32 UTC, moritzraho commented on lib/Files.js
> +    this.permissions = _permissions
please remove this

2020-08-19 09:32 UTC, moritzraho commented on lib/Files.js
> +   * @param {string} options.permissions premissions for presigned URL
could you add a validateInput for the options like in https://github.com/adobe/aio-lib-files/blob/784b6fffe07b2db369702983664020a9443d8153/lib/Files.js#L430 for example ?

2020-08-19 09:32 UTC, moritzraho commented on lib/impl/AzureBlobFiles.js
> +      options.permissions = this.permissions.READ
and here you can use Files.Permissions.Read instead of this

2020-09-23 08:30 UTC, sandeep-paliwal commented
@purplecabbage I have verified your changes around FilePermissions export, looks Good.

2020-09-23 18:00 UTC, purplecabbage approved these changes

2020-09-23 18:01 UTC, merged