Return file-info object
adobe/aio-lib-files pull request #69
Opened 2020-10-19 21:43 UTC by purplecabbage

Return file-info object with etag, contentLength, creationTime, contentType, ... from list and getProperties calls

## Description

List will return an array of:
{ name, creationTime, lastModified, etag, contentLength, contentType, isDirectory, isPublic, url }

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2020-10-20 09:39 UTC, moritzraho requested changes
One case is missing for list(file) when file is not a directory https://github.com/adobe/aio-lib-files/blob/d6ab8322a8e1ecdc08788625a1dc7222f2a1ff1c/lib/Files.js#L386 to be consistent in that case we should return this.getFileInfo(file)

2020-10-20 09:39 UTC, moritzraho commented on lib/impl/AzureBlobFiles.js
> +  async getFileInfo (filePath) {
I would make this function private and also add it into`lib/Files.js` in the `
  /* **************************** PRIVATE ABSTRACT METHODS TO IMPLEMENT ***************************** */` section. I think it should throw not implemented like other primitives and have some JSDOC to define the  interface (including return object -> typedef)

`getFileInfo` is part of the SPI now, it is a primitive that must be implemented by classes extending Files. (Files and subclasse(s) use the template pattern)

2020-10-20 09:39 UTC, moritzraho commented on lib/impl/AzureBlobFiles.js
> +        elements = elements.concat(response.segment.blobItems.map(blob => {
Same here the `_listFolder's` JSDoc in `Files.js` should be updated with expected new return format (SPI).
Also `list` JSDoc return value should be updated too (API)

2020-10-22 12:05 UTC, moritzraho reviewed
thanks for the changes, they LGTM 🙂 
(will approve when unit tests are added)

2020-11-11 04:50 UTC, shazron commented
unit tests are failing. GH Actions reports `Test Suites: 2 failed, 1 passed, 3 total
Tests:       12 failed, 197 passed, 209 total`

2020-12-08 05:14 UTC, merged